- hosts: all
  gather_facts: no
  tasks:
    - name: archive container image as a tarball
      docker_image:
        name: new-spring-petclinic:latest
        archive_path: spring-petclinic.tar
        source: local
        # state: present
    - name: copy tarball to host
      copy:
        src: ./spring-petclinic.tar
        dest: /root/spring-petclinic.tar
    - name: load container from tarball
      docker_image:
        name: new-spring-petclinic:latest
        load_path: /root/spring-petclinic.tar
        state: present
        source: local