# Specify the path to the jar file or the docker image name

---
- name: Provision hosts
  hosts: all
  become: yes
  become_method: sudo
  vars:
    file_path: "{{file}}" 

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    - name: Determine file type
      set_fact:
        file_type: "{{ file_path.split('.')[-1] }}"
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
    - name: Install Java (if file type is jar)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Docker (if file type is docker image)
      apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    
    - name: Install Terraform
      